const styles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    minHeight: { mobile: '441px', tablet: '481px' },
    width: { mobile: '280px', tablet: '608px' },
    boxShadow: '3px 8px 14px rgba(136, 198, 253, 0.19)',
    borderRadius: { mobile: '20px', tablet: '40px' },
    marginTop: { mobile: '44px', tablet: '70px' },
    marginLeft: 'auto',
    marginRight: 'auto',
    padding: { mobile: '35px 12px', tablet: '50px 75px' },
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: '500',
    fontSize: { mobile: '24px', tablet: '36px' },
    lineHeight: { mobile: '33px', tablet: '49px' },
    color: 'primary',
  },
  text: {
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontSize: { mobile: '12px', tablet: '14px', desktop: '16px' },
    lineHeight: { mobile: '16px', tablet: '19px', desktop: '22px' },
    color: '#888888',
  },
  linkT: {
    textDecoration: 'none',
    fontSize: { mobile: '12px', tablet: '14px', desktop: '16px' },
    lineHeight: { mobile: '16px', tablet: '19px', desktop: '22px' },
    color: '#54ADFF',
    textDecorationLine: 'underline',
  },
  textLink: {
    textAlign: 'center',
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontSize: { mobile: '12px', tablet: '14px', desktop: '16px' },
    lineHeight: { mobile: '16px', tablet: '19px', desktop: '22px' },
    textDecorationLine: 'none',
    color: '#888888',
    '&:hover': {
      color: '#54ADFF',
    },
  },
  button: {
    mt: { mobile: '20px', tablet: '30px' },
    textTransform: 'none',
    width: '100%',
    height: '48px',
    border: '2px solid #54ADFF',
    borderRadius: '40px',
    fontWeight: 600,
    fontSize: '20px',
    lineHeight: '27px',
    padding: '9px 20px',
    backgroundColor: 'rgba(84, 173, 255, 1)',
    color: 'rgba(255, 255, 255, 1)',
    '&:hover': {
      backgroundColor: '#54ADFF',
      color: '#FEF9F9',
    },

    '&:active': {
      backgroundColor: '#54ADFF',
      color: '#FEF9F9',
    },
    '&:focus': {
      backgroundColor: '#54ADFF',
      color: '#FEF9F9',
    },
  },
};

export default styles;
